lang: en
logo:
  $link: logo-white.svg
repo: https://github.com/atomicojs/atomicojs.github.io/tree/master
socials:
  github: atomicojs/atomico
  twitter: uppercod
menu:
  - title:
      es: Hooks
      en: Hooks
    category: hooks
  - title:
      es: Componentes
      en: Components
    category: components
aside:
  content:
    title: Contenido
